### ISSUE TITLE
Version should be bumped to 1.0

### ISSUE THREAD

**Issue by vecdeque** [kcmoot/gulp-css-asset-cachebuster#1]
Aside from the data URI issue, we've been using it on our project issue-free for almost 6 months. How do you feel about a version bump to 1.0?

**Comment by vbravest** [comment]
The current codebase is stable enough, but not pretty in any conceivable term (it's a direct fork of the original coffeescript output). My ideal "1.0" release would first involve a refactor to make the source a little friendlier to deal with.
